version: '3.3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - app
    volumes:
      - static:/label-studio/label_studio:rw
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/ssl/
    command: nginx -g "daemon off;"

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    expose:
      - "8080"
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-""}
    volumes:
      - ./mydata:/label-studio/data:rw
      - static:/label-studio/label_studio:rw



volumes:
  static: {} 
